#TODO Move to AWS Secrets Manager
stripe.secret.key=<stripe-secret-key>
stripe.create.session.url=https://api.stripe.com/v1/checkout/sessions
stripe.retrieve.session.url=https://api.stripe.com/v1/checkout/sessions/{id}
stripe.expire.session.url=https://api.stripe.com/v1/checkout/sessions/{id}/
payment.processing.notification.url=http://localhost:8082/v1/payments/notification
stripe.webhook.secret=<stripe-webhook-secret>

#spring.ai.openai.api-key=YourOpenAIKey

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b
# Start CMD : ollama run llama3.2:1bs

